# ENTROPY OF FOOTBALL STATISTICS

**In this document we will be conducting a search for frequent patterns. For that we will be converting non-binary columns in dataset to binary columns and then applying apriori algorithm to the aforemention transformed dataset.**

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [19]:
statistics = pd.DataFrame()
for i in range (2016, 2019, 1):
    foldername = "Parsed_" + str(i) + "_" + str(i+1)[2:] + "/gwgamesStats/"
    for j in range(1,39,1):
        filename = "gw" + str(j) + ".csv"
        statistics = statistics.append(pd.read_csv(foldername + filename))

In [20]:
statistics

                  name_h  attempted_passes_h  big_chances_created_h  \
0                Everton                 357                      0
1                Arsenal                 485                      0
2                Chelsea                 559                      0
3              Hull City                 448                      0
4          Middlesbrough                 353                      1
5        AFC Bournemouth                 483                      0
6        Manchester City                 678                      1
7            Southampton                 579                      0
8                Burnley                 336                      1
9         Crystal Palace                 415                      1
0        West Ham United                 355                      2
1                Watford                 330                      1
2             Sunderland                 401                      0
3         Leicester City                 360                      0
4                Burnley                 207                      0
5           Norwich City                 441                      2
6      Manchester United                 402                      0
7           Swansea City                 562                      1
8   West Bromwich Albion                 282                      3
9             Stoke City                 364                      1
0                Everton                 485                      1
1                Watford                 395                      0
2                Chelsea                 626                      3
3              Hull City                 395                      0
4         Leicester City                 409                      2
5        Manchester City                 587                      4
6            Southampton                 481                      0
7           Norwich City                 420                      1
8         Crystal Palace                 447                      0
9   West Bromwich Albion                 350                      0
0        West Ham United                 441                      1
1                Arsenal                 593                      1
2          Middlesbrough                 527                      1
3        AFC Bournemouth                 472                      0
4              Liverpool                 612                      5
5             Sunderland                 286                      0
6                Burnley                 394                      0
7           Swansea City                 399                      0
8      Manchester United                 376                      2
9             Stoke City                 327                      0
0                Everton                 541                      1
1                Watford                 286                      1
2                Chelsea                 542                      1
3              Hull City                 506                      0
4         Leicester City                 517                      4
5        Manchester City                 588                      4
6            Southampton                 443                      3
7           Norwich City                 615                      0
8   West Bromwich Albion                 254                      2
9         Crystal Palace                 466                      0
0        West Ham United                 368                      0
1                Arsenal                 534                      1
2          Middlesbrough                 389                      0
3        AFC Bournemouth                 421                      0
4              Liverpool                 763                      2
5             Sunderland                 361                      0
6                Burnley                 359                      0
7           Swansea City                 388                      1
8      Manchester United                 710                      3
9             Stoke City                 409                      1
0        West Ham United                 318                      0
1                Everton                 401                      1
2                Watford                 350                      1
3              Hull City                 377                      0
4             Sunderland                 426                      2
5         Leicester City                 395                      0
6                Burnley                 349                      1
7           Norwich City                 342                      0
8           Swansea City                 408                      3
9      Manchester United                 534                      5
0                Arsenal                 516                      5
1                Chelsea                 550                      4
2          Middlesbrough                 468                      0
3        AFC Bournemouth                 459                      0
4              Liverpool                 623                      0
5        Manchester City                 659                      0
6            Southampton                 551                      3
7   West Bromwich Albion                 230                      0
8         Crystal Palace                 406                      2
9             Stoke City                 480                      1
0        West Ham United                 543                      0
1                Arsenal                 707                      0
2                Chelsea                 448                      2
3              Hull City                 447                      0
4        AFC Bournemouth                 318                      0
5              Liverpool                 668                      4
6         Leicester City                 400                      2
7                Burnley                 286                      0
8        Manchester City                 585                      1
9           Swansea City                 444                      2
0                Everton                 407                      3
1                Watford                 474                      1
2          Middlesbrough                 358                      1
3             Sunderland                 299                      0
4            Southampton                 485                      0
5           Norwich City                 496                      0
6   West Bromwich Albion                 277                      0
7      Manchester United                 638                      2
8         Crystal Palace                 415                      0
9             Stoke City                 362                      3
0        West Ham United                 497                      0
1                Arsenal                 431                      0
2                Chelsea                 686                      0
3              Hull City                 319                      1
4        AFC Bournemouth                 534                      3
5              Liverpool                 563                      3
6         Leicester City                 520                      1
7                Burnley                 324                      1
8        Manchester City                 631                      2
9           Swansea City                 449                      1
0                Everton                 490                      2
1                Watford                 341                      1
2          Middlesbrough                 450                      0
3             Sunderland                 375                      0
4            Southampton                 371                      0
5   West Bromwich Albion                 401                      1
6           Norwich City                 595                      0
7      Manchester United                 444                      0
8         Crystal Palace                 274                      1
9             Stoke City                 364                      1
0                Arsenal                 467                      3
1                Watford                 356                      0
2                Chelsea                 388                      2
3              Hull City                 489                      0
4              Liverpool                 705                      0
5         Leicester City                 331                      0
6                Burnley                 267                      0
7            Southampton                 462                      4
8           Swansea City                 376                      0
9      Manchester United                 612                      3
0        West Ham United                 491                      0
1                Everton                 379                      1
2          Middlesbrough                 602                      3
3        AFC Bournemouth                 375                      0
4             Sunderland                 409                      0
5        Manchester City                 541                      2
6   West Bromwich Albion                 301                      1
7           Norwich City                 577                      1
8         Crystal Palace                 349                      1
9             Stoke City                 456                      1
0                Arsenal                 540                      1
1                Watford                 355                      3
2                Chelsea                 578                      0
3              Hull City                 447                      2
4              Liverpool                 627                      0
5         Leicester City                 209                      4
6                Burnley                 243                      2
7            Southampton                 503                      1
8           Swansea City                 475                      3
9      Manchester United                 286                      1
0        West Ham United                 440                      0
1                Everton                 357                      2
2         Crystal Palace                 397                      1
3          Middlesbrough                 385                      0
4        AFC Bournemouth                 536                      1
5             Sunderland                 316                      1
6        Manchester City                 504                      3
7   West Bromwich Albion                 351                      3
8           Norwich City                 672                      1
9             Stoke City                 231                      0
0        West Ham United                 417                      1
1                Everton                 286                      1
2         Crystal Palace                 478                      0
3          Middlesbrough                 411                      1
4        AFC Bournemouth                 449                      0
5             Sunderland                 272                      0
6        Manchester City                 594                      3
7   West Bromwich Albion                 412                      1
8           Norwich City                 481                      0
9             Stoke City                 575                      1
0                Arsenal                 817                      0
1                Watford                 352                      0
2                Chelsea                 472                      0
3              Hull City                 320                      0
4              Liverpool                 624                      0
5         Leicester City                 398                      1
6                Burnley                 301                      0
7            Southampton                 321                      0
8           Swansea City                 517                      0
9      Manchester United                 606                      2
0                Arsenal                 639                      1
1                Watford                 294                      0
2                Chelsea                 473                      1
3              Hull City                 402                      0
4              Liverpool                 435                      1
5         Leicester City                 309                      1
6                Burnley                 340                      2
7            Southampton                 570                      0
8           Swansea City                 455                      0
9      Manchester United                 611                      1
0        West Ham United                 401                      1
1                Everton                 482                      1
2         Crystal Palace                 403                      0
3          Middlesbrough                 534                      0
4        AFC Bournemouth                 377                      1
5             Sunderland                 291                      0
6        Manchester City                 450                      0
7   West Bromwich Albion                 347                      1
8           Norwich City                 440                      2
9             Stoke City                 401                      3
0        West Ham United                 342                      2
1                Everton                 274                      0
2                Watford                 348                      1
3              Hull City                 351                      1
4             Sunderland                 429                      1
5         Leicester City                 338                      0
6                Burnley                 294                      0
7           Norwich City                 670                      4
8           Swansea City                 444                      0
9      Manchester United                 491                      1
0                Arsenal                 578                      0
1         Crystal Palace                 368                      0
2                Chelsea                 557                      2
3          Middlesbrough                 518                      1
4        AFC Bournemouth                 525                      1
5              Liverpool                 784                      1
6        Manchester City                 474                      2
7            Southampton                 500                      0
8   West Bromwich Albion                 351                      2
9             Stoke City                 329                      0
0        West Ham United                 280                      1
1                Arsenal                 597                      0
2          Middlesbrough                 482                      0
3        AFC Bournemouth                 454                      0
4              Liverpool                 636                      1
5             Sunderland                 223                      0
6                Burnley                 415                      1
7           Swansea City                 417                      0
8      Manchester United                 635                      2
9             Stoke City                 416                      3
0                Everton                 478                      3
1         Crystal Palace                 491                      3
2                Watford                 512                      2
3                Chelsea                 408                      1
4              Hull City                 259                      2
5         Leicester City                 292                      0
6        Manchester City                 704                      3
7            Southampton                 474                      0
8   West Bromwich Albion                 312                      2
9           Norwich City                 579                      2
0        West Ham United                 532                      0
1                Arsenal                 485                      1
2          Middlesbrough                 463                      0
3        AFC Bournemouth                 359                      0
4              Liverpool                 421                      1
5             Sunderland                 443                      0
6                Burnley                 297                      1
7           Swansea City                 477                      1
8      Manchester United                 582                      6
9             Stoke City                 449                      1
0                Everton                 507                      2
1         Crystal Palace                 346                      0
2                Watford                 259                      0
3                Chelsea                 738                      0
4              Hull City                 464                      0
5         Leicester City                 281                      3
6   West Bromwich Albion                 297                      0
7           Norwich City                 583                      1
0        West Ham United                 558                      0
1                Watford                 252                      1
2              Liverpool                 455                      2
3             Sunderland                 288                      0
4         Leicester City                 396                      2
5        Manchester City                 626                      2
6   West Bromwich Albion                 369                      0
7           Norwich City                 453                      1
8           Swansea City                 578                      0
9      Manchester United                 617                      5
10            Stoke City                 435                      4
0                Everton                 599                      2
1              Hull City                 377                      2
2        AFC Bournemouth                 355                      2
3              Liverpool                 564                      0
0        West Ham United                 478                      2
1                Everton                 454                      3
2         Crystal Palace                 285                      1
3          Middlesbrough                 555                      0
4        AFC Bournemouth                 448                      1
5             Sunderland                 287                      2
6        Manchester City                 562                      5
7   West Bromwich Albion                 219                      3
8           Norwich City                 459                      0
9             Stoke City                 294                      0
0                Arsenal                 408                      1
1                Watford                 381                      1
2                Chelsea                 610                      2
3              Hull City                 383                      0
4              Liverpool                 468                      0
5         Leicester City                 392                      1
6                Burnley                 347                      0
7            Southampton                 552                      0
8           Swansea City                 416                      0
9      Manchester United                 762                      0

In [21]:
statistics.corr()["team_score_h"]

attempted_passes_h                   0.276039
big_chances_created_h                0.453036
big_chances_missed_h                 0.110446
clearances_blocks_interceptions_h   -0.071094
completed_passes_h                   0.290991
dribbles_h                           0.124129
errors_leading_to_goal_attempt_h    -0.084221
fixture_h                            0.021083
fouls_h                             -0.080247
key_passes_h                         0.332298
minutes_h                           -0.132444
offside_h                           -0.020561
open_play_crosses_h                 -0.087465
opponent_team_h                     -0.039168
penalties_conceded_h                -0.038431
penalties_missed_h                   0.017342
penalties_saved_h                    0.000477
recoveries_h                         0.023556
red_cards_h                         -0.037655
round_h                              0.020022
saves_h                             -0.113565
tackled_h                            0.036003
tackles_h                            0.005506
target_missed_h                      0.060274
team_score_h                         1.000000
yellow_cards_h                      -0.147405
shots_on_target_h                    0.616009
attempted_passes_a                  -0.176552
big_chances_created_a               -0.144484
big_chances_missed_a                -0.119671
clearances_blocks_interceptions_a   -0.101543
completed_passes_a                  -0.160427
dribbles_a                          -0.020794
errors_leading_to_goal_attempt_a     0.060661
fouls_a                             -0.022812
key_passes_a                        -0.191080
offside_a                           -0.007121
open_play_crosses_a                 -0.005473
penalties_conceded_a                 0.193796
penalties_missed_a                  -0.009309
penalties_saved_a                    0.018925
recoveries_a                        -0.112524
red_cards_a                          0.034797
saves_a                              0.162227
tackled_a                           -0.005795
tackles_a                           -0.015472
target_missed_a                     -0.119819
team_score_a                        -0.145656
yellow_cards_a                      -0.008609
shots_on_target_a                   -0.165524
Name: team_score_h, dtype: float64

In [22]:
# Displaying all descriptive informations for all columns. 
pd.set_option('display.max_columns', 50)
statistics.describe()

,attempted_passes_h,big_chances_created_h,big_chances_missed_h,clearances_blocks_interceptions_h,completed_passes_h,dribbles_h,errors_leading_to_goal_attempt_h,fixture_h,fouls_h,key_passes_h,minutes_h,offside_h,open_play_crosses_h,opponent_team_h,penalties_conceded_h,penalties_missed_h,penalties_saved_h,recoveries_h,red_cards_h,round_h,saves_h,tackled_h,tackles_h,target_missed_h,team_score_h,yellow_cards_h,shots_on_target_h,attempted_passes_a,big_chances_created_a,big_chances_missed_a,clearances_blocks_interceptions_a,completed_passes_a,dribbles_a,errors_leading_to_goal_attempt_a,fouls_a,key_passes_a,offside_a,open_play_crosses_a,penalties_conceded_a,penalties_missed_a,penalties_saved_a,recoveries_a,red_cards_a,saves_a,tackled_a,tackles_a,target_missed_a,team_score_a,yellow_cards_a,shots_on_target_a
count,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.00000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000
mean,461.819298,1.388596,1.065789,37.743860,368.271053,9.557895,0.271053,190.500000,10.488596,10.241228,33.392105,2.162281,3.280702,10.500000,0.103509,0.041228,0.012281,61.758772,0.049123,19.599123,2.633333,16.794737,8.257018,5.385088,1.565789,1.592105,4.730702,438.903509,1.131579,0.875439,43.107895,344.393860,8.882456,0.300877,10.809649,8.27807,1.864912,2.538596,0.150000,0.018421,0.035088,60.679825,0.062281,3.164912,16.754386,8.200877,4.338596,1.200877,1.718421,3.834211
std,140.103589,1.397619,1.184501,12.842095,142.749986,4.429645,0.536012,109.744315,3.351890,4.831731,40.763324,1.704968,2.184263,5.768812,0.307623,0.207545,0.110184,8.379742,0.224193,11.088035,1.837263,5.220340,3.774329,2.745248,1.319159,1.254782,2.711522,135.715693,1.178630,1.032532,13.459911,137.579911,4.262692,0.569798,3.507635,3.94061,1.576606,1.871955,0.392366,0.134527,0.188791,8.691581,0.245375,2.164645,5.119917,3.895812,2.329583,1.195176,1.266372,2.312250
min,176.000000,0.000000,0.000000,4.000000,94.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,37.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,173.000000,0.000000,0.000000,10.000000,91.000000,0.000000,0.000000,3.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,33.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,361.000000,0.000000,0.000000,29.000000,264.000000,6.000000,0.000000,95.750000,8.000000,7.000000,0.000000,1.000000,2.000000,5.750000,0.000000,0.000000,0.000000,56.000000,0.000000,10.000000,1.000000,13.000000,5.000000,3.000000,1.000000,1.000000,3.000000,339.000000,0.000000,0.000000,33.000000,240.000000,6.000000,0.000000,8.000000,5.00000,1.000000,1.000000,0.000000,0.000000,0.000000,55.000000,0.000000,2.000000,13.000000,5.000000,3.000000,0.000000,1.000000,2.000000
50%,444.000000,1.000000,1.000000,37.000000,348.500000,9.000000,0.000000,190.500000,10.000000,10.000000,0.000000,2.000000,3.000000,10.500000,0.000000,0.000000,0.000000,62.000000,0.000000,19.500000,2.000000,16.000000,8.000000,5.000000,1.000000,1.000000,4.000000,417.000000,1.000000,1.000000,42.500000,322.000000,8.000000,0.000000,10.000000,8.00000,2.000000,2.000000,0.000000,0.000000,0.000000,61.000000,0.000000,3.000000,16.000000,8.000000,4.000000,1.000000,2.000000,4.000000
75%,549.250000,2.000000,2.000000,46.000000,458.250000,12.000000,0.000000,285.250000,13.000000,13.000000,90.000000,3.000000,4.000000,15.250000,0.000000,0.000000,0.000000,67.000000,0.000000,29.000000,4.000000,20.000000,11.000000,7.000000,2.000000,2.000000,6.000000,526.000000,2.000000,1.000000,51.000000,433.000000,11.000000,1.000000,13.000000,11.00000,3.000000,4.000000,0.000000,0.000000,0.000000,66.250000,0.000000,4.000000,20.000000,11.000000,6.000000,2.000000,2.000000,5.000000
max,1015.000000,8.000000,6.000000,97.000000,942.000000,28.000000,3.000000,380.000000,24.000000,32.000000,90.000000,10.000000,13.000000,20.000000,2.000000,2.000000,1.000000,94.000000,2.000000,38.000000,13.000000,38.000000,24.000000,16.000000,7.000000,6.000000,17.000000,975.000000,7.000000,6.000000,94.000000,903.000000,26.000000,3.000000,26.000000,22.00000,10.000000,13.000000,2.000000,1.000000,2.000000,90.000000,2.000000,14.000000,33.000000,26.000000,14.000000,7.000000,7.000000,15.000000

In [81]:
def encode_numeric_to_binary(dataframe, column_name, ranges, is_single=False):
    # Method generates binary columns from user defined ranges.
    #     dataframe : pandas dataframe, where the binary columns are put.
    #     column_name : the column that is transformed into binary columns.
    #     is_single : truth value that determines whether values in ranges array are interpreted as columns individually or in pairs.
    
    if is_single:
        for i in range(0,len(ranges)):
            binary_column_name = column_name + "_" + str(ranges[i])
            dataframe[binary_column_name] = np.where((dataframe[column_name] == ranges[i]), 1, 0)
    else:
        for i in range(0,len(ranges)):
            binary_column_name = column_name + "_" + str(ranges[i][0]) + "_" + str(ranges[i][1])
            dataframe[binary_column_name] = np.where((ranges[i][0] <= dataframe[column_name])&(dataframe[column_name] <= ranges[i][1]), 1, 0)
            

    return dataframe.drop(columns=[column_name], axis=1)

def generate_ranges(dataframe, column_name, slices=10):
    #print(dataframe.describe())
    print(column_name + ": " , end="")
    mean = dataframe[column_name].mean()
    s_deviation = dataframe[column_name].std()
    min_value = dataframe[column_name].min()
    max_value = dataframe[column_name].max()
    print("Mean=", mean, "; S_dev=", s_deviation, "; min_value=", min_value, "; max_value:", max_value)
    generated_ranges = []
    last_value = 0
    for i, value in enumerate([min_value] + list(range(int(mean-s_deviation), int(mean+s_deviation)+1, max(1, int(int(mean+s_deviation) - int(mean-s_deviation))//slices))) + [max_value]):
        if(i != 0 and last_value >= 0 and value > 0):
            generated_ranges.append((last_value, value-1))
        last_value = value
    return generated_ranges
            
        
statistics_binary = statistics.copy(deep=True)

for suffix in ["_h", "_a"]:
    if (suffix == "_h"):
        statistics_binary = statistics_binary.drop(columns=['fixture'+suffix, 'round'+suffix, 'minutes'+suffix, 'opponent_team'+suffix], axis=1)

    # Transforming numeric columns into binary columns.
    # Encoding attempted passes
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'attempted_passes'+suffix, generate_ranges(statistics, 'attempted_passes'+suffix))
    # Encoding big_chances_created
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'big_chances_created'+suffix, [1,2,3,4,5,6,7,8], 1)
    # Encoding big_chances_missed0
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'big_chances_missed'+suffix, [1,2,3,4,5,6], 1)
    # Encoding clearances_blocks_interceptions
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'clearances_blocks_interceptions'+suffix, generate_ranges(statistics, 'clearances_blocks_interceptions'+suffix))
    # Encoding completed_passes
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'completed_passes'+suffix, generate_ranges(statistics, 'completed_passes'+suffix))
    # Encoding dribbles
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'dribbles'+suffix, generate_ranges(statistics, 'dribbles'+suffix))
    # Encoding errors_leading_to_goal_attempt
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'errors_leading_to_goal_attempt'+suffix, [1,2,3,4], 1)
    # Encoding fouls
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'fouls'+suffix, generate_ranges(statistics, 'fouls'+suffix))
    # Encoding key_passes
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'key_passes'+suffix, generate_ranges(statistics, 'key_passes'+suffix))
    # Encoding offside
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'offside'+suffix, generate_ranges(statistics, 'offside'+suffix))
    # Encoding open_play_crosses
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'open_play_crosses'+suffix, generate_ranges(statistics, 'open_play_crosses'+suffix))
    # Encoding opponent_team
    #statistics_binary = encode_numeric_to_binary(statistics_binary, 'opponent_team'+suffix, list(range(20)), 1)
    # Encoding penalties_conceded
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'penalties_conceded'+suffix, [1,2], 1)
    # Encoding penalties_missed
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'penalties_missed'+suffix, [1,2], 1)
    # Encoding penalties_saved
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'penalties_saved'+suffix, [1,2], 1)
    # Encoding recoveries
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'recoveries'+suffix, generate_ranges(statistics, 'recoveries'+suffix))
    # Encoding red_cards
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'red_cards'+suffix, [1,2], 1)
    # Encoding saves
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'saves'+suffix, generate_ranges(statistics, 'saves'+suffix))
    # Encoding tackled
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'tackled'+suffix, generate_ranges(statistics, 'tackled'+suffix))
    # Encoding tackles
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'tackles'+suffix, generate_ranges(statistics, 'tackles'+suffix))
    # Encoding target_missed
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'target_missed'+suffix, generate_ranges(statistics, 'target_missed'+suffix))
    # Encoding team_score
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'team_score'+suffix, [0,1,2,3,4,5,6,7],1)
    # Encoding yellow_cards
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'yellow_cards'+suffix, generate_ranges(statistics, 'yellow_cards'+suffix))
    # Encoding shots_on_target
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'shots_on_target'+suffix, generate_ranges(statistics, 'shots_on_target'+suffix))
    # Encoding name
    for name in list(statistics_binary["name"+suffix].unique()):
        statistics_binary[name] = np.where((statistics_binary["name"+suffix] == name), 1, 0)
    statistics_binary = statistics_binary.drop(columns=["name"+suffix], axis=1)

"""
# Dropping useless columns.
for suffix in ["_h", "_a"]:
    if (suffix == "_h"):
        statistics_binary = statistics_binary.drop(columns=['fixture'+suffix, 'round'+suffix, 'minutes'+suffix, 'opponent_team'+suffix], axis=1)

    # Transforming numeric columns into binary columns.
    # Encoding attempted passes
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'attempted_passes'+suffix, [(0,249), (250,539), (540,1015)])
    # Encoding big_chances_created
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'big_chances_created'+suffix, [0,1,2,3,4,5,6,7,8], 1)
    # Encoding big_chances_missed0
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'big_chances_missed'+suffix, [0,1,2,3,4,5,6], 1)
    # Encoding clearances_blocks_interceptions
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'clearances_blocks_interceptions'+suffix, [(10,19), (20,39), (40,49), (50,59), (60,69), (70,79), (80,89), (90,99)])
    # Encoding completed_passes
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'completed_passes'+suffix, [(0,249), (250,539), (540,1015)])
    # Encoding dribbles
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'dribbles'+suffix, [(0,0),(0,1),(2,5),(6,12),(13,28)])
    # Encoding errors_leading_to_goal_attempt
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'errors_leading_to_goal_attempt'+suffix, [1,2,3,4], 1)
    # Encoding fouls
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'fouls'+suffix, [(0,1),(2,7),(8,13),(14,26)])
    # Encoding key_passes
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'key_passes'+suffix, [(0,5), (6,12), (13,32)])
    # Encoding offside
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'offside'+suffix, [(0,1), (2,3), (4,10)])
    # Encoding open_play_crosses
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'open_play_crosses'+suffix, [(0,0), (1,4), (5,10)])
    # Encoding opponent_team
    #statistics_binary = encode_numeric_to_binary(statistics_binary, 'opponent_team'+suffix, list(range(20)), 1)
    # Encoding penalties_conceded
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'penalties_conceded'+suffix, [1,2], 1)
    # Encoding penalties_missed
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'penalties_missed'+suffix, [1,2], 1)
    # Encoding penalties_saved
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'penalties_saved'+suffix, [1,2], 1)
    # Encoding recoveries
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'recoveries'+suffix, [(20,54), (55,66), (67,94)])
    # Encoding red_cards
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'red_cards'+suffix, [1, 2], 1)
    # Encoding saves
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'saves'+suffix, [(0,1), (2,5), (6,14)])
    # Encoding tackled
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'tackled'+suffix, [(0,1), (2,11), (12,19), (20,38)])
    # Encoding tackles
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'tackles'+suffix, [(0,1),(2,4),(5,10),(11,26)])
    # Encoding target_missed
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'target_missed'+suffix, [(0,1),(2,6),(7,16)])
    # Encoding team_score
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'team_score'+suffix, [0,1,2,3,4,5,6,7],1)
    # Encoding yellow_cards
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'yellow_cards'+suffix, [(0,0), (1,2), (3,16)])
    # Encoding shots_on_target
    statistics_binary = encode_numeric_to_binary(statistics_binary, 'shots_on_target'+suffix, [(0,0), (1,2), (3,9), (10,17)])
    # Encoding name
    for name in list(statistics_binary["name"+suffix].unique()):
        statistics_binary[name] = np.where((statistics_binary["name"+suffix] == name), 1, 0)
    statistics_binary = statistics_binary.drop(columns=["name"+suffix], axis=1)
statistics_binary
"""    
pd.set_option('display.max_rows', 5)
pd.set_option('display.max_columns', 400)
statistics_binary

attempted_passes_h: Mean= 461.81929824561405 ; S_dev= 140.10358884118443 ; min_value= 176 ; max_value: 1015
clearances_blocks_interceptions_h: Mean= 37.743859649122804 ; S_dev= 12.842095200792558 ; min_value= 4 ; max_value: 97
completed_passes_h: Mean= 368.2710526315789 ; S_dev= 142.74998633771494 ; min_value= 94 ; max_value: 942
dribbles_h: Mean= 9.557894736842105 ; S_dev= 4.429645019872293 ; min_value= 0 ; max_value: 28
fouls_h: Mean= 10.488596491228071 ; S_dev= 3.3518896108709253 ; min_value= 0 ; max_value: 24
key_passes_h: Mean= 10.241228070175438 ; S_dev= 4.831730638847264 ; min_value= 0 ; max_value: 32
offside_h: Mean= 2.162280701754386 ; S_dev= 1.7049682270102668 ; min_value= 0 ; max_value: 10
open_play_crosses_h: Mean= 3.280701754385965 ; S_dev= 2.1842631830551658 ; min_value= 0 ; max_value: 13
recoveries_h: Mean= 61.75877192982456 ; S_dev= 8.37974177641666 ; min_value= 37 ; max_value: 94
saves_h: Mean= 2.6333333333333333 ; S_dev= 1.8372626633757956 ; min_value= 0 ; max_value: 13
tackled_h: Mean= 16.794736842105262 ; S_dev= 5.220339806169817 ; min_value= 0 ; max_value: 38
tackles_h: Mean= 8.257017543859648 ; S_dev= 3.7743291980449083 ; min_value= 0 ; max_value: 24
target_missed_h: Mean= 5.385087719298245 ; S_dev= 2.7452483477786966 ; min_value= 0 ; max_value: 16
yellow_cards_h: Mean= 1.5921052631578947 ; S_dev= 1.254781529896177 ; min_value= 0 ; max_value: 6
shots_on_target_h: Mean= 4.730701754385965 ; S_dev= 2.711521516866939 ; min_value= 0 ; max_value: 17
attempted_passes_a: Mean= 438.9035087719298 ; S_dev= 135.71569268661995 ; min_value= 173 ; max_value: 975
clearances_blocks_interceptions_a: Mean= 43.107894736842105 ; S_dev= 13.45991117760497 ; min_value= 10 ; max_value: 94
completed_passes_a: Mean= 344.3938596491228 ; S_dev= 137.57991103399064 ; min_value= 91 ; max_value: 903
dribbles_a: Mean= 8.882456140350877 ; S_dev= 4.262692056317786 ; min_value= 0 ; max_value: 26
fouls_a: Mean= 10.809649122807018 ; S_dev= 3.5076354516255845 ; min_value= 3 ; max_value: 26
key_passes_a: Mean= 8.278070175438597 ; S_dev= 3.94060955277197 ; min_value= 0 ; max_value: 22
offside_a: Mean= 1.8649122807017544 ; S_dev= 1.576605886225596 ; min_value= 0 ; max_value: 10
open_play_crosses_a: Mean= 2.5385964912280703 ; S_dev= 1.8719550644416638 ; min_value= 0 ; max_value: 13
recoveries_a: Mean= 60.67982456140351 ; S_dev= 8.69158090032497 ; min_value= 33 ; max_value: 90
saves_a: Mean= 3.1649122807017545 ; S_dev= 2.1646445713976172 ; min_value= 0 ; max_value: 14
tackled_a: Mean= 16.75438596491228 ; S_dev= 5.119916530248543 ; min_value= 0 ; max_value: 33
tackles_a: Mean= 8.200877192982457 ; S_dev= 3.89581156900815 ; min_value= 0 ; max_value: 26
target_missed_a: Mean= 4.338596491228071 ; S_dev= 2.3295825824040937 ; min_value= 0 ; max_value: 14
yellow_cards_a: Mean= 1.7184210526315788 ; S_dev= 1.2663723770178013 ; min_value= 0 ; max_value: 7
shots_on_target_a: Mean= 3.8342105263157893 ; S_dev= 2.3122504211424593 ; min_value= 0 ; max_value: 15

,attempted_passes_h_176_320,attempted_passes_h_321_348,attempted_passes_h_349_376,attempted_passes_h_377_404,attempted_passes_h_405_432,attempted_passes_h_433_460,attempted_passes_h_461_488,attempted_passes_h_489_516,attempted_passes_h_517_544,attempted_passes_h_545_572,attempted_passes_h_573_600,attempted_passes_h_601_1014,big_chances_created_h_1,big_chances_created_h_2,big_chances_created_h_3,big_chances_created_h_4,big_chances_created_h_5,big_chances_created_h_6,big_chances_created_h_7,big_chances_created_h_8,big_chances_missed_h_1,big_chances_missed_h_2,big_chances_missed_h_3,big_chances_missed_h_4,big_chances_missed_h_5,big_chances_missed_h_6,clearances_blocks_interceptions_h_4_23,clearances_blocks_interceptions_h_24_25,clearances_blocks_interceptions_h_26_27,clearances_blocks_interceptions_h_28_29,clearances_blocks_interceptions_h_30_31,clearances_blocks_interceptions_h_32_33,clearances_blocks_interceptions_h_34_35,clearances_blocks_interceptions_h_36_37,clearances_blocks_interceptions_h_38_39,clearances_blocks_interceptions_h_40_41,clearances_blocks_interceptions_h_42_43,clearances_blocks_interceptions_h_44_45,clearances_blocks_interceptions_h_46_47,clearances_blocks_interceptions_h_48_49,clearances_blocks_interceptions_h_50_96,completed_passes_h_94_224,completed_passes_h_225_252,completed_passes_h_253_280,completed_passes_h_281_308,completed_passes_h_309_336,completed_passes_h_337_364,completed_passes_h_365_392,completed_passes_h_393_420,completed_passes_h_421_448,completed_passes_h_449_476,completed_passes_h_477_504,completed_passes_h_505_941,dribbles_h_0_4,dribbles_h_5_5,dribbles_h_6_6,dribbles_h_7_7,dribbles_h_8_8,dribbles_h_9_9,dribbles_h_10_10,dribbles_h_11_11,dribbles_h_12_12,dribbles_h_13_27,errors_leading_to_goal_attempt_h_1,errors_leading_to_goal_attempt_h_2,errors_leading_to_goal_attempt_h_3,errors_leading_to_goal_attempt_h_4,fouls_h_0_6,fouls_h_7_7,fouls_h_8_8,fouls_h_9_9,fouls_h_10_10,fouls_h_11_11,fouls_h_12_12,fouls_h_13_23,key_passes_h_0_4,key_passes_h_5_5,key_passes_h_6_6,key_passes_h_7_7,key_passes_h_8_8,key_passes_h_9_9,key_passes_h_10_10,key_passes_h_11_11,key_passes_h_12_12,key_passes_h_13_13,key_passes_h_14_14,key_passes_h_15_31,offside_h_0_0,offside_h_1_1,offside_h_2_2,offside_h_3_9,open_play_crosses_h_0_0,open_play_crosses_h_1_1,open_play_crosses_h_2_2,open_play_crosses_h_3_3,open_play_crosses_h_4_4,open_play_crosses_h_5_12,penalties_conceded_h_1,penalties_conceded_h_2,penalties_missed_h_1,penalties_missed_h_2,penalties_saved_h_1,penalties_saved_h_2,recoveries_h_37_52,recoveries_h_53_53,recoveries_h_54_54,recoveries_h_55_55,recoveries_h_56_56,recoveries_h_57_57,recoveries_h_58_58,recoveries_h_59_59,recoveries_h_60_60,recoveries_h_61_61,recoveries_h_62_62,recoveries_h_63_63,recoveries_h_64_64,recoveries_h_65_65,recoveries_h_66_66,recoveries_h_67_67,recoveries_h_68_68,recoveries_h_69_69,recoveries_h_70_93,red_cards_h_1,red_cards_h_2,saves_h_0_0,saves_h_1_1,saves_h_2_2,saves_h_3_3,saves_h_4_12,tackled_h_0_10,tackled_h_11_11,tackled_h_12_12,tackled_h_13_13,tackled_h_14_14,tackled_h_15_15,tackled_h_16_16,tackled_h_17_17,tackled_h_18_18,tackled_h_19_19,tackled_h_20_20,tackled_h_21_21,tackled_h_22_37,tackles_h_0_3,tackles_h_4_4,tackles_h_5_5,tackles_h_6_6,tackles_h_7_7,tackles_h_8_8,tackles_h_9_9,tackles_h_10_10,tackles_h_11_11,tackles_h_12_23,target_missed_h_0_1,target_missed_h_2_2,target_missed_h_3_3,target_missed_h_4_4,target_missed_h_5_5,target_missed_h_6_6,target_missed_h_7_7,target_missed_h_8_15,team_score_h_0,team_score_h_1,team_score_h_2,team_score_h_3,team_score_h_4,team_score_h_5,team_score_h_6,team_score_h_7,yellow_cards_h_0_0,yellow_cards_h_1_1,yellow_cards_h_2_5,shots_on_target_h_0_1,shots_on_target_h_2_2,shots_on_target_h_3_3,shots_on_target_h_4_4,shots_on_target_h_5_5,shots_on_target_h_6_6,shots_on_target_h_7_16,Everton,Arsenal,Chelsea,Hull City,Middlesbrough,AFC Bournemouth,Manchester City,Southampton,Burnley,Crystal Palace,West Ham United,Watford,Sunderland,Leicester City,Norwich City,Manchester United,Swansea City,West Bromwich Albion,Stoke City,Liverpool,Newcastle United,Brighton,Huddersfield Town,Tottenham,Fulham,Wolves,Cardiff City,attempted_passes_a_173_302,attempted_passes_a_303_329,attempted_passes_a_330_356,attempted_passes_a_357_383,attempted_passes_a_384_410,attempted_passes_a_411_437,attempted_passes_a_438_464,attempted_passes_a_465_491,attempted_passes_a_492_518,attempted_passes_a_519_545,attempted_passes_a_546_572,attempted_passes_a_573_974,big_chances_created_a_1,big_chances_created_a_2,big_chances_created_a_3,big_chances_created_a_4,big_chances_created_a_5,big_chances_created_a_6,big_chances_created_a_7,big_chances_created_a_8,big_chances_missed_a_1,big_chances_missed_a_2,big_chances_missed_a_3,big_chances_missed_a_4,big_chances_missed_a_5,big_chances_missed_a_6,clearances_blocks_interceptions_a_10_28,clearances_blocks_interceptions_a_29_30,clearances_blocks_interceptions_a_31_32,clearances_blocks_interceptions_a_33_34,clearances_blocks_interceptions_a_35_36,clearances_blocks_interceptions_a_37_38,clearances_blocks_interceptions_a_39_40,clearances_blocks_interceptions_a_41_42,clearances_blocks_interceptions_a_43_44,clearances_blocks_interceptions_a_45_46,clearances_blocks_interceptions_a_47_48,clearances_blocks_interceptions_a_49_50,clearances_blocks_interceptions_a_51_52,clearances_blocks_interceptions_a_53_54,clearances_blocks_interceptions_a_55_93,completed_passes_a_91_205,completed_passes_a_206_232,completed_passes_a_233_259,completed_passes_a_260_286,completed_passes_a_287_313,completed_passes_a_314_340,completed_passes_a_341_367,completed_passes_a_368_394,completed_passes_a_395_421,completed_passes_a_422_448,completed_passes_a_449_475,completed_passes_a_476_902,dribbles_a_0_3,dribbles_a_4_4,dribbles_a_5_5,dribbles_a_6_6,dribbles_a_7_7,dribbles_a_8_8,dribbles_a_9_9,dribbles_a_10_10,dribbles_a_11_11,dribbles_a_12_12,dribbles_a_13_25,errors_leading_to_goal_attempt_a_1,errors_leading_to_goal_attempt_a_2,errors_leading_to_goal_attempt_a_3,errors_leading_to_goal_attempt_a_4,fouls_a_3_6,fouls_a_7_7,fouls_a_8_8,fouls_a_9_9,fouls_a_10_10,fouls_a_11_11,fouls_a_12_12,fouls_a_13_13,fouls_a_14_25,key_passes_a_0_3,key_passes_a_4_4,key_passes_a_5_5,key_passes_a_6_6,key_passes_a_7_7,key_passes_a_8_8,key_passes_a_9_9,key_passes_a_10_10,key_passes_a_11_11,key_passes_a_12_21,offside_a_0_0,offside_a_1_1,offside_a_2_2,offside_a_3_9,open_play_crosses_a_0_0,open_play_crosses_a_1_1,open_play_crosses_a_2_2,open_play_crosses_a_3_3,open_play_crosses_a_4_12,penalties_conceded_a_1,penalties_conceded_a_2,penalties_missed_a_1,penalties_missed_a_2,penalties_saved_a_1,penalties_saved_a_2,recoveries_a_33_50,recoveries_a_51_51,recoveries_a_52_52,recoveries_a_53_53,recoveries_a_54_54,recoveries_a_55_55,recoveries_a_56_56,recoveries_a_57_57,recoveries_a_58_58,recoveries_a_59_59,recoveries_a_60_60,recoveries_a_61_61,recoveries_a_62_62,recoveries_a_63_63,recoveries_a_64_64,recoveries_a_65_65,recoveries_a_66_66,recoveries_a_67_67,recoveries_a_68_68,recoveries_a_69_89,red_cards_a_1,red_cards_a_2,saves_a_0_0,saves_a_1_1,saves_a_2_2,saves_a_3_3,saves_a_4_4,saves_a_5_13,tackled_a_0_10,tackled_a_11_11,tackled_a_12_12,tackled_a_13_13,tackled_a_14_14,tackled_a_15_15,tackled_a_16_16,tackled_a_17_17,tackled_a_18_18,tackled_a_19_19,tackled_a_20_20,tackled_a_21_32,tackles_a_0_3,tackles_a_4_4,tackles_a_5_5,tackles_a_6_6,tackles_a_7_7,tackles_a_8_8,tackles_a_9_9,tackles_a_10_10,tackles_a_11_11,tackles_a_12_25,target_missed_a_0_1,target_missed_a_2_2,target_missed_a_3_3,target_missed_a_4_4,target_missed_a_5_5,target_missed_a_6_13,team_score_a_0,team_score_a_1,team_score_a_2,team_score_a_3,team_score_a_4,team_score_a_5,team_score_a_6,team_score_a_7,yellow_cards_a_0_0,yellow_cards_a_1_1,yellow_cards_a_2_6,shots_on_target_a_0_0,shots_on_target_a_1_1,shots_on_target_a_2_2,shots_on_target_a_3_3,shots_on_target_a_4_4,shots_on_target_a_5_5,shots_on_target_a_6_14
0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
9,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1

In [88]:
import mlxtend
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

# Finding frequent patterns in dataset
pd.set_option('display.max_rows', 1200)
pd.set_option('display.max_colwidth', 200)
frequent_itemset = apriori(statistics_binary, min_support=0.1, use_colnames=True)
frequent_itemset

# Finding rules
mlx_rules = association_rules(frequent_itemset, metric='confidence', min_threshold=0.62)
mlx_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(completed_passes_h_94_224),(attempted_passes_h_176_320),0.153509,0.152632,0.140351,0.914286,5.990148,0.116921,9.885965
1,(attempted_passes_h_176_320),(completed_passes_h_94_224),0.152632,0.153509,0.140351,0.919540,5.990148,0.116921,10.520677
2,(attempted_passes_h_601_1014),(completed_passes_h_505_941),0.164912,0.171930,0.161404,0.978723,5.692575,0.133050,38.919298
3,(completed_passes_h_505_941),(attempted_passes_h_601_1014),0.171930,0.164912,0.161404,0.938776,5.692575,0.133050,13.639766
4,(fouls_h_13_23),(yellow_cards_h_2_5),0.257895,0.482456,0.171930,0.666667,1.381818,0.047507,1.552632
5,(key_passes_a_12_21),(saves_h_4_12),0.200877,0.297368,0.128947,0.641921,2.158674,0.069213,1.962227
6,(shots_on_target_a_6_14),(saves_h_4_12),0.225439,0.297368,0.192105,0.852140,2.865604,0.125067,4.752008
7,(saves_h_4_12),(shots_on_target_a_6_14),0.297368,0.225439,0.192105,0.646018,2.865604,0.125067,2.188136
8,(shots_on_target_h_7_16),(saves_a_5_13),0.229825,0.235088,0.173684,0.755725,3.214652,0.119655,3.131360
9,(saves_a_5_13),(shots_on_target_h_7_16),0.235088,0.229825,0.173684,0.738806,3.214652,0.119655,2.948672
10,(completed_passes_a_91_205),(attempted_passes_a_173_302),0.152632,0.155263,0.137719,0.902299,5.811416,0.114021,8.646130
11,(attempted_passes_a_173_302),(completed_passes_a_91_205),0.155263,0.152632,0.137719,0.887006,5.811416,0.114021,7.499211
12,(attempted_passes_a_573_974),(completed_passes_a_476_902),0.164035,0.172807,0.155263,0.946524,5.477347,0.126917,15.468509
13,(completed_passes_a_476_902),(attempted_passes_a_573_974),0.172807,0.164035,0.155263,0.898477,5.477347,0.126917,8.234254
14,(fouls_a_14_25),(yellow_cards_a_2_6),0.219298,0.523684,0.161404,0.736000,1.405427,0.046560,1.804226
15,(key_passes_a_12_21),(target_missed_a_6_13),0.200877,0.273684,0.130702,0.650655,2.377393,0.075725,2.079079
16,"(yellow_cards_a_2_6, fouls_h_13_23)",(yellow_cards_h_2_5),0.150877,0.482456,0.105263,0.697674,1.446089,0.032472,1.711876
17,"(shots_on_target_a_6_14, yellow_cards_h_2_5)",(saves_h_4_12),0.122807,0.297368,0.102632,0.835714,2.810367,0.066113,4.276888
18,"(saves_h_4_12, yellow_cards_h_2_5)",(shots_on_target_a_6_14),0.154386,0.225439,0.102632,0.664773,2.948797,0.067827,2.310556
19,"(shots_on_target_a_6_14, key_passes_a_12_21)",(saves_h_4_12),0.113158,0.297368,0.102632,0.906977,3.050010,0.068982,7.553289
20,"(saves_h_4_12, key_passes_a_12_21)",(shots_on_target_a_6_14),0.128947,0.225439,0.102632,0.795918,3.530533,0.073562,3.795351
21,"(yellow_cards_a_2_6, shots_on_target_h_7_16)",(saves_a_5_13),0.128947,0.235088,0.106140,0.823129,3.501371,0.075826,4.324696
22,"(yellow_cards_a_2_6, saves_a_5_13)",(shots_on_target_h_7_16),0.138596,0.229825,0.106140,0.765823,3.332206,0.074287,3.288857