# ENTROPY OF FOOTBALL STATISTICS

**In this project we will be exploring football statistics and the effectivness of machine learning models to predict the outcome of matches. For this we will be employing two types of models: regression and classifier models.**

In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [3]:
statistics = pd.DataFrame()
for i in range (2016, 2019, 1):
    foldername = "Parsed_" + str(i) + "_" + str(i+1)[2:] + "/gwgames/"
    for j in range(1,39,1):
        filename = "gw" + str(j) + ".csv"
        statistics = statistics.append(pd.read_csv(foldername + filename))

In [4]:
statistics

,name,attempted_passes,big_chances_created,big_chances_missed,clearances_blocks_interceptions,completed_passes,dribbles,errors_leading_to_goal_attempt,fixture,fouls,...,red_cards,round,saves,tackled,tackles,target_missed,team_score,was_home,yellow_cards,shots_on_target
0,West Ham United,351,0,0,49,262,3,0,10,16,...,0,1,4,19,18,2,1,0,2,3
1,Everton,357,0,1,61,261,8,0,3,10,...,0,1,3,16,16,4,1,1,0,6
2,Arsenal,485,0,1,36,385,8,0,8,13,...,0,1,3,23,8,3,3,1,3,5
3,Watford,303,0,0,51,194,8,0,7,12,...,1,1,6,13,15,4,1,0,2,1
4,Chelsea,559,0,0,19,481,16,0,10,16,...,0,1,2,26,10,6,2,1,5,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,Cardiff City,225,1,0,38,131,7,0,377,6,...,0,38,10,16,7,6,2,0,3,4
16,Tottenham,540,0,0,31,449,7,0,379,10,...,0,38,7,19,8,5,2,1,0,3
17,Brighton,245,1,0,55,176,4,1,371,12,...,0,38,5,15,3,3,1,1,0,2
18,Newcastle United,359,2,1,55,282,4,0,374,8,...,0,38,2,12,4,6,4,0,0,6
19,Manchester City,792,2,1,18,734,11,0,371,8,...,0,38,1,17,8,3,4,0,0,9

In [5]:
statistics.corr()["team_score"]

attempted_passes                   0.275663
big_chances_created                0.469892
big_chances_missed                 0.128034
clearances_blocks_interceptions   -0.080473
completed_passes                   0.287806
dribbles                           0.146018
errors_leading_to_goal_attempt    -0.051728
fixture                            0.000264
fouls                             -0.058021
key_passes                         0.358543
minutes                           -0.085692
offside                           -0.019444
open_play_crosses                 -0.029384
opponent_team                     -0.007060
penalties_conceded                -0.031049
penalties_missed                   0.021531
penalties_saved                   -0.028282
recoveries                         0.044236
red_cards                         -0.034767
round                             -0.000705
saves                             -0.146882
tackled                            0.040189
tackles                            0.019968
target_missed                      0.089336
team_score                         1.000000
was_home                           0.143519
yellow_cards                      -0.084689
shots_on_target                    0.624668
Name: team_score, dtype: float64

In [6]:
red_carded_teams = statistics[statistics["red_cards"] == 1]
not_red_carded_teams = statistics[statistics["red_cards"] == 0]
red_carded_teams.mean()
not_red_carded_teams.mean()

attempted_passes                   453.702226
big_chances_created                  1.268089
big_chances_missed                   0.980519
clearances_blocks_interceptions     40.262059
completed_passes                   359.596939
dribbles                             9.269481
errors_leading_to_goal_attempt       0.286642
fixture                            191.658163
fouls                               10.607607
key_passes                           9.360853
minutes                             33.239796
offside                              2.020408
open_play_crosses                    2.937848
opponent_team                       10.573748
penalties_conceded                   0.118275
penalties_missed                     0.030148
penalties_saved                      0.023191
recoveries                          61.365955
red_cards                            0.000000
round                               19.709184
saves                                2.865955
tackled                             16.811688
tackles                              8.244434
target_missed                        4.923933
team_score                           1.393785
was_home                             0.503711
yellow_cards                         1.655844
shots_on_target                      4.307050
dtype: float64

In [63]:
#for col_name in statistics_binary.columns:
#    print("# Encoding " + col_name)

# Encoding name
# Encoding big_chances_missed
# Encoding clearances_blocks_interceptions
# Encoding completed_passes
# Encoding dribbles
# Encoding errors_leading_to_goal_attempt
# Encoding fixture
# Encoding fouls
# Encoding key_passes
# Encoding minutes
# Encoding offside
# Encoding open_play_crosses
# Encoding opponent_team
# Encoding penalties_conceded
# Encoding penalties_missed
# Encoding penalties_saved
# Encoding recoveries
# Encoding red_cards
# Encoding round
# Encoding saves
# Encoding tackled
# Encoding tackles
# Encoding target_missed
# Encoding team_score
# Encoding was_home
# Encoding yellow_cards
# Encoding shots_on_target
# Encoding attempted_passes_0_200
# Encoding attempted_passes_200_400
# Encoding attempted_passes_400_600
# Encoding attempted_passes_600_800
# Encoding attempted_passes_800_1000
# Encoding attempted_passes_1000_1200
# Encoding attempted_passes_0_1
# Encoding attempted_passes_1_2
# Encoding attempted_passes_2_3
# Encoding attempted_passes_3_4
# Encoding attempted_passes_4_5
# Encoding attempted_passes_5_6
# Encoding attempted_passes_6_7

In [67]:
statistics.describe()

,attempted_passes,big_chances_created,big_chances_missed,clearances_blocks_interceptions,completed_passes,dribbles,errors_leading_to_goal_attempt,fixture,fouls,key_passes,...,red_cards,round,saves,tackled,tackles,target_missed,team_score,was_home,yellow_cards,shots_on_target
count,2280.000000,2280.000000,2280.000000,2280.000000,2280.000000,2280.000000,2280.000000,2280.000000,2280.000000,2280.000000,...,2280.000000,2280.000000,2280.000000,2280.000000,2280.000000,2280.000000,2280.000000,2280.00000,2280.000000,2280.000000
mean,450.361404,1.260088,0.970614,40.425877,356.332456,9.220175,0.285965,190.500000,10.649123,9.259649,...,0.055702,19.599123,2.899123,16.774561,8.228947,4.861842,1.383333,0.50000,1.655263,4.282456
std,138.372237,1.298862,1.114945,13.422546,140.665790,4.359124,0.553243,109.720235,3.433650,4.515795,...,0.235064,11.085602,2.024726,5.169277,3.834813,2.598602,1.271583,0.50011,1.261896,2.558838
min,173.000000,0.000000,0.000000,4.000000,91.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,350.750000,0.000000,0.000000,31.000000,252.000000,6.000000,0.000000,95.750000,8.000000,6.000000,...,0.000000,10.000000,1.000000,13.000000,5.000000,3.000000,0.000000,0.00000,1.000000,2.000000
50%,428.000000,1.000000,1.000000,40.000000,332.500000,9.000000,0.000000,190.500000,10.000000,9.000000,...,0.000000,19.500000,3.000000,16.000000,8.000000,5.000000,1.000000,0.50000,2.000000,4.000000
75%,539.250000,2.000000,2.000000,49.000000,446.000000,12.000000,0.000000,285.250000,13.000000,12.000000,...,0.000000,29.000000,4.000000,20.000000,11.000000,6.000000,2.000000,1.00000,2.000000,6.000000
max,1015.000000,8.000000,6.000000,97.000000,942.000000,28.000000,3.000000,380.000000,26.000000,32.000000,...,2.000000,38.000000,14.000000,38.000000,26.000000,16.000000,7.000000,1.00000,7.000000,17.000000

In [73]:
def encode_numeric_to_binary(dataframe, column_name, ranges, is_single=False):
    
    for i in range(1,len(ranges)):
        if is_single:
            binary_column_name = column_name + "_" + str(ranges[i-1])
        else:
            binary_column_name = column_name + "_" + str(ranges[i-1]) + "_" + str(ranges[i])
                
        dataframe[binary_column_name] = np.where((ranges[i-1] < dataframe[column_name])&(dataframe[column_name] <= ranges[i]), 1, 0)


   
    return dataframe.drop(columns=[column_name], axis=1)
    
    
# Transforming numeric columns into binary columns.
statistics_binary = statistics.copy(deep=True)


# Encoding attempted passes
statistics_binary = encode_numeric_to_binary(statistics_binary, 'attempted_passes', [0,200,400,600,800,1000,1200])
# Encoding big_chances_created
statistics_binary = encode_numeric_to_binary(statistics_binary, 'big_chances_created', list(range(statistics_binary['big_chances_created'].max()+1)), 1)
# Encoding big_chances_missed
statistics_binary = encode_numeric_to_binary(statistics_binary, 'big_chances_missed', list(range(statistics_binary['big_chances_missed'].max()+1)), 1)
# Encoding clearances_blocks_interceptions
statistics_binary = encode_numeric_to_binary(statistics_binary, 'clearances_blocks_interceptions', list(range(0, 101, 10)))
# Encoding completed_passes
statistics_binary
# Encoding dribbles
# Encoding errors_leading_to_goal_attempt
# Encoding fixture
# Encoding fouls
# Encoding key_passes
# Encoding minutes
# Encoding offside
# Encoding open_play_crosses
# Encoding opponent_team
# Encoding penalties_conceded
# Encoding penalties_missed
# Encoding penalties_saved
# Encoding recoveries
# Encoding red_cards
# Encoding round
# Encoding saves
# Encoding tackled
# Encoding tackles
# Encoding target_missed
# Encoding team_score
# Encoding was_home
# Encoding yellow_cards
# Encoding shots_on_target

,name,completed_passes,dribbles,errors_leading_to_goal_attempt,fixture,fouls,key_passes,minutes,offside,open_play_crosses,...,clearances_blocks_interceptions_0_10,clearances_blocks_interceptions_10_20,clearances_blocks_interceptions_20_30,clearances_blocks_interceptions_30_40,clearances_blocks_interceptions_40_50,clearances_blocks_interceptions_50_60,clearances_blocks_interceptions_60_70,clearances_blocks_interceptions_70_80,clearances_blocks_interceptions_80_90,clearances_blocks_interceptions_90_100
0,West Ham United,262,3,0,10,16,4,0,1,0,...,0,0,0,0,1,0,0,0,0,0
1,Everton,261,8,0,3,10,9,15,5,1,...,0,0,0,0,0,0,1,0,0,0
2,Arsenal,385,8,0,8,13,6,60,4,5,...,0,0,0,1,0,0,0,0,0,0
3,Watford,194,8,0,7,12,4,0,0,1,...,0,0,0,0,0,1,0,0,0,0
4,Chelsea,481,16,0,10,16,11,0,1,2,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,Cardiff City,131,7,0,377,6,8,0,0,0,...,0,0,0,1,0,0,0,0,0,0
16,Tottenham,449,7,0,379,10,7,0,2,0,...,0,0,0,1,0,0,0,0,0,0
17,Brighton,176,4,1,371,12,4,66,1,2,...,0,0,0,0,0,1,0,0,0,0
18,Newcastle United,282,4,0,374,8,9,0,1,1,...,0,0,0,0,0,1,0,0,0,0
19,Manchester City,734,11,0,371,8,15,0,1,1,...,0,1,0,0,0,0,0,0,0,0